--DESAFIO 1
SELECT COD_PRODUTO, 
       DESCRICAO, 
       'ANTES DO AUMENTO' AS QUANDO, 
       VALOR_UNITARIO 
FROM PRODUTO
UNION
SELECT COD_PRODUTO, 
       DESCRICAO, 
       'DEPOIS DO AUMENTO' AS QUANDO, 
       VALOR_UNITARIO * 1.1 AS VALOR_UNITARIO 
FROM PRODUTO
ORDER BY COD_PRODUTO, QUANDO;

--DESAFIO 2
SELECT COD_PRODUTO, 
       DESCRICAO, 
       VALOR_UNITARIO 
FROM PRODUTO
UNION
SELECT  0  AS COD_PRODUTO,
        'SOMA DOS VALORES' AS DESCRICAO,
        SUM(VALOR_UNITARIO) AS TOTAL_UNITARIO
FROM PRODUTO
ORDER BY VALOR_UNITARIO;

