/*//////////////////////////  PARTE 2.1 - CRIANDO E MANIPULANDO O BANCO DE DADOS //////////////////////////*/
--EXERCICIO 3
ALTER TABLE CLIENTE
MODIFY ENDERECO VARCHAR2(30);

--EXERCICIO 4
ALTER TABLE ITEM_PEDIDO
ADD PCO_UNIT NUMERIC(6,2);

--EXERCICIO 5
UPDATE CLIENTE
SET CEP = '18035-400'
WHERE CIDADE = 'SOROCABA';

--EXERCICO 6
UPDATE PEDIDO
SET PRAZO_ENTREGA = PRAZO_ENTREGA + 10
WHERE NUM_PEDIDO = 78945; 

--EXERCICIO 7
UPDATE PRODUTO
SET VALOR_UNITARIO = VALOR_UNITARIO * 1.1
WHERE UNIDADE = 'UN';

--EXERCICIO 8
DELETE FROM PRODUTO
WHERE UNIDADE = 'CX' AND VALOR_UNITARIO > 50;
/*Nota caso o produto tenha sido referenciado em item_pedido não poderá ser excluido (restrição mãe-filha)*/




/*//////////////////////////  PARTE 2.2 - CRIANDO E MANIPULANDO O BANCO DE DADOS //////////////////////////*/
--EXERCICIO 1
SELECT NUM_PEDIDO, PRAZO_ENTREGA FROM PEDIDO;

--EXERCICIO 2
SELECT DESCRICAO, VALOR_UNITARIO FROM PRODUTO;

--EXERCICIO 3
SELECT NOME_CLIENTE, ENDERECO FROM CLIENTE;

--EXERCICIO 4
SELECT NOME_VENDEDOR FROM VENDEDOR;

--EXERCICIO 5
SELECT * FROM CLIENTE;

--EXERCICIO 6
SELECT * FROM PRODUTO;

--EXERCICIO 7
SELECT NOME_VENDEDOR AS NOME FROM VENDEDOR;

--EXERCICIO 8
SELECT COD_PRODUTO, VALOR_UNITARIO, SUM(VALOR_UNITARIO * 1.1) AS AUMENTO
FROM PRODUTO
GROUP BY COD_PRODUTO, VALOR_UNITARIO;

--EXERCICIO 9
SELECT SALARIO_FIXO, SUM(SALARIO_FIXO * 1.05) AS AUMENTO
FROM VENDEDOR
GROUP BY SALARIO_FIXO;

--EXERCICIO 10
SELECT NOME_CLIENTE
FROM CLIENTE
WHERE CIDADE = 'SOROCABA';

--EXERCICIO 11
SELECT * FROM VENDEDOR
WHERE SALARIO_FIXO < 1900;

--EXERCICIO 12
SELECT COD_PRODUTO, DESCRICAO
FROM PRODUTO
WHERE UNIDADE = 'UN';

--EXERCICIO 13
SELECT NUM_PEDIDO
FROM PEDIDO
WHERE PRAZO_ENTREGA
BETWEEN '01/01/2018' AND '28/03/2019';

--EXERCICIO 14
SELECT NUM_PEDIDO, PRAZO_ENTREGA
FROM PEDIDO
WHERE PRAZO_ENTREGA
BETWEEN '01/01/2019' AND '31/12/2019';

--EXERCICIO 15
SELECT * FROM PRODUTO
WHERE VALOR_UNITARIO
BETWEEN 10 AND 2000;

--EXERCICIO 16
SELECT NUM_PEDIDO, COD_PRODUTO, QUANTIDADE
FROM ITEM_PEDIDO
WHERE QUANTIDADE BETWEEN 1 AND 2;

--EXERCICIO 17
SELECT NOME_VENDEDOR
FROM VENDEDOR
WHERE NOME_VENDEDOR LIKE 'AMAIA%';

--EXERCICIO 18
SELECT NOME_VENDEDOR
FROM VENDEDOR
WHERE NOME_VENDEDOR LIKE '%MENDEZ';

--EXERCICIO 19
SELECT DESCRICAO, COD_PRODUTO
FROM PRODUTO
WHERE DESCRICAO LIKE '%IA%';

--EXERCICIO 20
SELECT * FROM CLIENTE
WHERE ENDERECO IS NULL;

--EXERCICIO 21
SELECT DISTINCT CIDADE FROM CLIENTE;

--EXERCICIO 22
SELECT * FROM CLIENTE
ORDER BY NOME_CLIENTE ASC;

--EXERCICIO 23
SELECT * FROM CLIENTE
ORDER BY NOME_CLIENTE DESC;

--EXERCICIO 24
SELECT * FROM CLIENTE
ORDER BY CIDADE, NOME_CLIENTE;

--EXERCICIO 25
SELECT COD_PRODUTO, DESCRICAO
FROM PRODUTO
WHERE UNIDADE = 'UN'
ORDER BY DESCRICAO;