/*
SELECT - NEW
DELETE - OLD
UPDATE - NEW E OLD
*/

/*2. Escreva um trigger que ao alterar o prazo de entrega de um pedido, 
grave na tablog o prazo antigo, prazo novo e o nome do cliente.*/
CREATE TABLE TAB_LOG_NEW(
    COD           NUMBER,
    HORA          DATE,
    USUARIO       VARCHAR2(20),
    TABELA        VARCHAR(20),
    VALOR_ANTIGO  VARCHAR(20),
    VALOR_NOVO    VARCHAR(20),
    CAMPO         VARCHAR2(180)
);

CREATE SEQUENCE SEGNEW;

CREATE OR REPLACE TRIGGER ALTERA_PRAZO_ENTREGA
BEFORE UPDATE OF PRAZO_ENTREGA ON PEDIDO
FOR EACH ROW
DECLARE
    VNOME_CLI   CLIENTE.NOME_CLIENTE%TYPE;
    VCOD_CLI    CLIENTE.COD_CLIENTE%TYPE;
BEGIN
    
    SELECT NOME_CLIENTE INTO VNOME_CLI
    FROM CLIENTE
    WHERE CLIENTE.COD_CLIENTE = :NEW.COD_CLIENTE;
    
    INSERT INTO TAB_LOG_NEW 
    VALUES (SEGNEW.nextval, SYSDATE, USER, 'PEDIDO', :OLD.PRAZO_ENTREGA, :NEW.PRAZO_ENTREGA, 'COLUNA: PRAZO_ENTREGA DO CLIENTE: ' || VNOME_CLI);
    
END ALTERA_PRAZO_ENTREGA;


UPDATE PEDIDO
SET PRAZO_ENTREGA = PRAZO_ENTREGA + 30
WHERE NUM_PEDIDO = 78949;

UPDATE PEDIDO
SET PRAZO_ENTREGA = PRAZO_ENTREGA + 30
WHERE NUM_PEDIDO = 78950;

UPDATE PEDIDO
SET PRAZO_ENTREGA = PRAZO_ENTREGA + 10
WHERE NUM_PEDIDO = 78952;

SELECT * FROM TAB_LOG_NEW;